#!/bin/sh
#/etc/init.d/raspiREST-API

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

APP_PATH=`pwd`

case "$1" in
start)
exec forever --sourceDir=$APP_PATH -p $APP_PATH app.js
;;
stop)
exec forever stop --sourceDir=$APP_PATH app.js
;;
*)
echo "Usage: /etc/init.d/raspiREST-API {start|stop}"
exit 1
;;
esac
exit 0
