#!/bin/sh

set -e

echo "Installing raspiREST-API as Service"

APP_PATH=`pwd`
USER_NAME=`whoami`

sudo cp $APP_PATH/config/raspiREST-API /etc/init.d/raspiREST-API
sudo chmod a+x /etc/init.d/raspiREST-API
sudo update-rc.d raspiREST-API defaults
/etc/init.d/raspiREST-API start

echo "raspiREST-API is running..."
