#!/bin/sh

set -e

echo "Installing raspiREST-API as Service"

APP_PATH=`pwd`

sudo cp $APP_PATH/config/raspiRESTapi /etc/init.d/raspiRESTapi
sudo chmod a+x /etc/init.d/raspiRESTapi
sudo update-rc.d raspiRESTapi defaults
sudo systemctl stop raspiRESTapi.service
sudo systemctl start raspiRESTapi.service

echo "raspiREST-API is running..."
